### PYTHON BASICS

* CONTENTS:
    * Basic Operations in python
    * Numpy arrays
    * Numpy indexing and selecting
    * Numpy operations
    

In [41]:
7**4 #Returns the 4th power of 7

2401

In [42]:
s = 'Hi there Sam!' 
s.split() #Splits the string

['Hi', 'there', 'Sam!']

In [43]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter)) #The .format method formats the specified value(s) and insert them inside the string's placeholder. The placeholder is defined using curly brackets: {}

The diameter of Earth is 12742 kilometers.


In [45]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(lst[3][1][2]) #Used to Extract the item from the nested list. This give the list as a whole
lst[3][1][2][0] # The index 0 is used to get the element from the list.

['hello']


'hello'

In [48]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]} 
d['k1'][3]['tricky'][3]['target'][3] #Used to get the element 'hello' from the nested dictionary

'hello'

In [49]:
def domainGet(email): #Create a function to get 'domain.com' with the email-id passed as the arguement
    return email.split('@')[-1] #Splits the email and return the value at the end of the list
domainGet('user@domain.com') #Func call statement

'domain.com'

In [50]:
def findDog(st): #Def the funtion to find if the word dog is there in the given sentence
    return 'dog' in st.lower().split()  #Converts the string to all lower case to avoid error and then splits the sentence, checks if the dog is there or not
findDog('Is there a dog here?')

True

In [51]:
def countDog(st): #Creates a function to get the count of "dog" in the given sentence
    count = 0 
    for word in st.lower().split(): #Converts the given string into lower and split the string based on each whitespace
        if word == 'dog': #Checks if the word is "dog", if yes, then the count variable is increased by 1
            count += 1
    return count
countDog('This dog runs faster than the other dog dude!') #Function Call Statement

2

In [52]:
seq = ['soup','dog','salad','cat','great']
list(filter(lambda word: word[0]=='s',seq)) #Using a lambda function to get the elements that start with letter s from the given list

['soup', 'salad']

In [54]:
def caught_speeding(speed, is_birthday): #You are driving a little too fast, and a police officer stops you. Write a function to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". If your speed is 60 or less, the result is "No Ticket". If speed is between 61 and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all cases.
    
    if is_birthday:
        speeding = speed - 5 #Changing the speed if it was their birthday
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

In [55]:
caught_speeding(81,True)

'Small Ticket'

In [56]:
caught_speeding(81,False)

'Big Ticket'

### UDEMY ML& DS
* Shift+Enter=Gives the output & inserts a new line
* Shift+Tab after using the paranthesis =Gives Information about the syntax
* Hashtag is used to comment
* Tab = Gives suggestions to Complete the Keyword

### NUMPY ARRAYS

In [1]:
import numpy as np #Imports lib numpy

In [2]:
mat=[1,2,3]  #declaring a list to a variable
print(type(mat)) #prints the type of the list
print(mat) #prints the content of the variable 

<class 'list'>
[1, 2, 3]


In [3]:
np.array(mat) #Converting the list to an array using 'np.array'

array([1, 2, 3])

In [4]:
np_mat=np.array(mat)
print(np_mat)  #prints the array content
print(type(np_mat)) # prints the type: to check if the list has been converted to an array

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
matrix=[[1,2,3],[4,5,6],[7,8,9]] #Declaring a 3 items in the list
print(matrix) # Prints the list with the items

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
np_matrix=np.array(matrix) # converts the list into a matrix
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(1,100) #'np.arange(start value,stop value(excluding),step increaments)' prints the range of value within the given limit

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
np.arange(100,0,-20)

array([100,  80,  60,  40,  20])

In [19]:
np.zeros(5) #Returns values of 0 as float as per the shape given in the paranthesis

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,5)) #Retruns values of 0 as float as a tuple of 3 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(5) #Returns 1D vector of 5 1's

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0,10,3) #Return evenly spaced numbers over a specified interval. linspace(start_value,stop_value,num of elements to be included within the specified range that has to be equally spaced)

array([ 0.,  5., 10.])

In [26]:
np.linspace(0,10,11) #Evenly spaced number is given as 11, because we want to include the end point. 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
len(np.linspace(0,10,11)) #The length should be 11 as we have included 10 and the start value is 0

11

In [28]:
np.eye(6) #Creates an Identity matrix, which has the same number of rows and columns with 1's in the diagonal and 0's elsewhere

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.random.rand(1)

array([0.48741334])

In [32]:
np.random.rand(5,6) #Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``

array([[0.51884212, 0.48908527, 0.62280027, 0.63425768, 0.78051708,
        0.28014669],
       [0.26464074, 0.54892896, 0.86024163, 0.25624491, 0.91414908,
        0.95502595],
       [0.68360769, 0.95348403, 0.23321177, 0.46244406, 0.24185042,
        0.10558796],
       [0.22399447, 0.51365106, 0.66370392, 0.47828527, 0.24095159,
        0.22086841],
       [0.95014773, 0.78243596, 0.75596548, 0.01846444, 0.92894627,
        0.64308462]])

In [33]:
np.random.rand(2,3)

array([[0.26282063, 0.28333433, 0.71042761],
       [0.84271656, 0.23793017, 0.79178116]])

In [34]:
np.random.randn(2,3) #Gives Random Standard Normal Distribution, which can also include negative values and the value tend to lie close to zero

array([[ 0.69677781,  0.25699765, -0.28904426],
       [ 1.249291  , -0.07582967,  0.15083524]])

In [36]:
np.random.randint(2,101,5) #Gives Random integer Values within the shape, randint(start_value,stop_value(exclusive),No of integers to be printed/the shape to be printed)

8

In [37]:
np.random.randint(2,100,5)

array([36, 73, 50, 78, 41])

In [38]:
np.random.randint(2,100,(3,5))

array([[67, 13, 14, 59, 83],
       [35, 62, 21, 75, 64],
       [64, 37, 20, 75, 62]])

In [39]:
np.random.seed(42) # Used to set random state so that the values can be reproduced ; allows us to set the random numbers
np.random.rand(4) # Picks 4 random Values between 0 and 1

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [40]:
np.random.seed(101) #The seed and the rand should be used in the same cell to get the reproduced random number
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [57]:
arr=np.arange(0,25)

In [58]:
arr.reshape(5,5) #Reshapes the array in the given shape format. Note that the array element size and the shape should be equal

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
ranarr =np.random.randint(1,100,10) #Creates a set of 10 random values and saves it in the variable ranarr

In [63]:
ranarr

array([10, 78, 41,  5, 64, 41, 61, 93, 65,  6])

In [64]:
ranarr.max() #Gets the maximum value of the array

93

In [65]:
ranarr.min() #Gets the minimum value of the array

5

In [66]:
ranarr.dtype #Gets the Datatype of the array

dtype('int32')

In [67]:
ranarr.argmax() #Gives the index Location of the maximum value of the array

7

In [68]:
ranarr.argmin() #Gives the index Location of the minimum value of the array

3

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
 arr.shape #Gives the shape of the array. (25,0) is because the arr is a one-d vector

(25,)

In [72]:
arr=arr.reshape(1,25) #Reshapes the given array as 1 row and 25 Columns within the tuple

In [73]:
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [74]:
arr=arr.reshape(25,1) #Reshapes the given array as 25Columns and 1 Row

In [75]:
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### NUMPY INDEXING AND SELECTING

In [76]:
import numpy as np

In [77]:
arr=np.arange(0,100,10)

In [78]:
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [79]:
arr[2] #Gets the value at the second index

20

In [80]:
arr[0:]  #Gets the value from the element 0 to the end of the array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
arr[:5]  #Gets the value from the begining to the 5th element of the array

array([ 0, 10, 20, 30, 40])

In [82]:
arr[6:] #Gets the elememts from the 6th index to the end of the array

array([60, 70, 80, 90])

In [85]:
arr[0:5]=100 #Used for broadcasting, here the value 100 is set to the indecies from o to 5
arr

array([100, 100, 100, 100, 100,  50,  60,  70,  80,  90])

In [89]:
slice_of_array= arr[0:5] #Slice_of_array takes the values of 0-5th element from arr
slice_of_array

array([0, 1, 2, 3, 4])

In [91]:
slice_of_array[:]=66 #Assigning the value 66 to all the elements of "slice_of_array"
slice_of_array

array([66, 66, 66, 66, 66])

In [92]:
arr #The arr array is modified when the slice is modified as the slice points to the arr array.

array([66, 66, 66, 66, 66,  5,  6,  7,  8,  9, 10])

In [94]:
arr_copy=arr.copy() #To not have the modifications reflected in the main array, we have to make a copy of the array
arr_copy[1:5]=70 #Inclusive of the begining index and excluding the ending index
arr_copy

array([66, 70, 70, 70, 70,  5,  6,  7,  8,  9, 10])

In [95]:
arr

array([66, 66, 66, 66, 66,  5,  6,  7,  8,  9, 10])

In [97]:
arr_2d=np.array([[5,10,15],[2,4,6],[10,20,30]]) #Show the elements in the form of matrix
arr_2d

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [10, 20, 30]])

In [100]:
arr_2d.shape #Gives the shape of the array; no of rows, no of columns

(3, 3)

In [104]:
print(arr_2d[0]) #Prints the first row of the 2D array
print(arr_2d[1,1]) #Prints the second row and second element
print(arr_2d[2,0]) # Prints the third row, first element

[ 5 10 15]
4
10


In [108]:
arr_Sliced=arr_2d[:2,1:] #To slice the array and get only the first and second rows, second and third column
arr_Sliced

array([[10, 15],
       [ 4,  6]])

In [118]:
arr=np.arange(0,26,2) #Get Values between 0 and 100, with 10 values as interval
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [119]:
arr>4 #Conditional Broadcast; Checks each element in the array to see if it is greater than 4 

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [122]:
Bool_arr=arr>4 # Assigns the Condition to a variable so that it can be passed to other arrays as conditions
print(Bool_arr)
print(arr[Bool_arr]) #Prints the original array for which the given condition is true ; arr[Bool_arr]==arr[arr>4] => Bool_arr=arr>4

[False False False  True  True  True  True  True  True  True  True  True
  True]
[ 6  8 10 12 14 16 18 20 22 24]


### NUMPY OPERATIONS

In [128]:
import numpy as np

In [130]:
 arr= np.arange(0,10) #Gets the range of values from 0 to 10
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr+5 #Adds 5 to each element in the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [132]:
arr+arr # Adds the array to the same array; but note that the shape of both the array should be the same

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [133]:
arr/arr #0 divided by 0 shows an error and the value of 0/0 is given as not a number(nan )

C:\Users\Manikandan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [134]:
np.sqrt(arr) #Prints the square root of the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [137]:
print(np.cos(arr)) #Prints the Cosine of the array
print(np.sin(arr)) #Prints the Sine of the array

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [136]:
np.log(arr) #Prints the log of the array and shows a warning as we have infinity (1/0) in the solution

C:\Users\Manikandan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [138]:
print(arr.sum()) #Prints the sum of the array
print(arr.max()) #Prints the maximum value of the array
print(arr.mean()) #Prints the Average of the array
print(arr.var()) #Prints the expectation of the squared deviation of a random variable from its mean.
print(arr.std()) #Prints the  dispersion of a dataset relative to its mean and is calculated as the square root of the variance

45
9
4.5
8.25
2.8722813232690143


In [140]:
arr_2d=np.arange(0,25).reshape(5,5) #Creates a 2D array with the values from 0 to 25 and reshapes it as 5*5 matrix
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
arr_2d.sum() #Gets the sum of the entire Matrix

300

In [145]:
arr_2d.sum(axis=0) #Prints the sum of the elements across the rows; axis=0 denotes the sum is to be performed across the rows; sum(a00+a10+a20+a30+a40)=result's first element, sum(a01+a11+a21+a31+a41)=result's second element and so on.

array([50, 55, 60, 65, 70])

In [147]:
arr_2d.sum(axis=1) #Prints the sum of the elements across the columns; axis=1 denotes the sum is to be performed across the columns; sum(a00+a01+a02+a03+a04)=result's first element, sum(a10+a11+a12+a13+a14)=result's second element and so on.

array([ 10,  35,  60,  85, 110])